packages:
  base: !include 
    file: base.yaml
    vars:
      api_key: !secret mirror-light-01_api_key
      ota_password: !secret mirror-light-01_ota_password
  device_type: !include ../../../device_types/mirror-light.yaml
  linked-light: !include
    file: ../../../templates/double_linked-light.yaml
    vars:
      light_id: sylvania_smart_plus
      key: !secret mirror-light-01_udp_key
      name_1: ${area}-mirror-light-02
      key_1: !secret mirror-light-02_udp_key
      name_2: ${area}-mirror-light-03
      key_2: !secret mirror-light-03_udp_key

substitutions:
  node_name: "mirror-light-01"
  friendly_name: "Greyson's Bathroom Mirror Light"