packages:
  base: !include
    file: base.yaml
    vars:
      api_key: !secret ceiling_fan_light_02_api_key
      ota_password: !secret ceiling_fan_light_02_ota_password
  device_type: !include ../../../device_types/ceiling_fan_light.yaml

substitutions:
  node_name: "ceiling_fan_light_02"
  friendly_name: "Greyon's Room Ceiling Fan Light"
  dns_name: "ceiling-fan-light-02"
