packages:
  base: !include
    file: base.yaml
    vars:
      api_key: !secret closet_light_api_key
      ota_password: !secret closet_light_ota_password
  device_type: !include ../../../device_types/closet_light.yaml

substitutions:
  node_name: "closet_light"
  friendly_name: "Greyson's Closet Light"
  dns_name: "closet-light"
