packages:
  base: !include 
    file: base.yaml
    vars:
      api_key: !secret mirror_light_02_api_key
      ota_password: !secret mirror_light_02_ota_password
  mirrordevice_type_light: !include ../../../device_types/mirror_light.yaml
  linked_light: !include
    file: ../../../templates/double_linked_light.yaml
    vars:
      light_id: sylvania_smart_plus
      key: !secret mirror_light_02_udp_key
      name_1: ${area}_mirror_light_01
      key_1: !secret mirror_light_01_udp_key
      name_2: ${area}_mirror_light_03
      key_2: !secret mirror_light_03_udp_key

substitutions:
  node_name: "mirror_light_02"
  friendly_name: "Downstairs Bathroom Mirror Light"