packages:
  base: !include
    file: base.yaml
    vars:
      api_key: !secret ceiling_light_01_api_key
      ota_password: !secret ceiling_light_01_ota_password
  device_type: !include ../../../device_types/ceiling_light.yaml

substitutions:
  node_name: "ceiling_light_01"
  friendly_name: "Dining Room Ceiling Light"
  dns_name: "ceiling-light-01"
