packages:
  base: !include
    file: base.yaml
    vars:
      api_key: !secret ceiling_light_api_key
      ota_password: !secret ceiling_light_ota_password
  device_type: !include ../../../device_types/ceiling_light.yaml

substitutions:
  node_name: "ceiling_light"
  friendly_name: "Entryway Ceiling Light"
  dns_name: "ceiling-light"
