packages:
  base: !include 
    file: base.yaml
    vars:
      api_key: !secret wall_lamp_api_key
      ota_password: !secret wall_lamp_ota_password
  device_type: !include ../../../device_types/wall_lamp_light.yaml

substitutions:
  node_name: "wall_lamp"
  friendly_name: "Balcony Wall Lamp"