#"bargraph" + green LED feedback whenever slider moves
sensor:
  - platform: template
    id: slider_sensor
    name: "Touch Slider Brightness (Decoupled)"
    unit_of_measurement: "%"
    accuracy_decimals: 0
    update_interval: 50ms   # poll frequently for low‐latency
    on_value:
      then:
        - lambda: |-
            float percent = x;
            if (percent <= 0.0f) {
              // Bargraph LED: always show one bar when “zero”
              uint8_t bar_cmd = 0x40 | 1;  // 0x41
              id(uart_bus).write_array(&bar_cmd, 1);
              // Locally turn OFF green LED when slider = 0
              id(green_led).turn_off();
            } else {
              // Bargraph: map 0..100% → 1..7
              int bar_level = int((percent / 100.0f) * 6.0f + 1.0f + 0.5f);
              if (bar_level < 1) bar_level = 1;
              if (bar_level > 7) bar_level = 7;
              uint8_t bar_cmd = 0x40 | bar_level;  // 0x41..0x47
              id(uart_bus).write_array(&bar_cmd, 1);

              // Locally turn ON green LED whenever slider > 0
              id(green_led).turn_on();
            }