sensor:
  - platform: template
    id: slider_sensor
    name: "Touch Slider Brightness"
    unit_of_measurement: "%"
    accuracy_decimals: 0
    update_interval: 50ms
    on_value:
      then:
        - lambda: |-
            float perc = x;
            id(dimmer_slider).publish_state(perc);
            if (perc <= 0.0f) {
              uint8_t bar_cmd = 0x41;
              id(uart_bus).write_array(&bar_cmd, 1);
              id(green_led).turn_off();
            } else {
              int bar_level = int((perc / 100.0f) * 6.0f + 1.0f + 0.5f);
              if (bar_level < 1) bar_level = 1;
              if (bar_level > 7) bar_level = 7;
              uint8_t bar_cmd = 0x40 | bar_level;
              id(uart_bus).write_array(&bar_cmd, 1);
              id(green_led).turn_on();
            }
            int dim_val = int(perc + 0.5f);
            if (dim_val < 0) dim_val = 0;
            if (dim_val > 100) dim_val = 100;
            uint8_t dim_cmd = 0x80 | dim_val;
            delay(14);
            id(uart_bus).write_array(&dim_cmd, 1);