packages:
  base: !include 
    file: base.yaml
    vars:
      api_key: !secret bar-light-01_api_key
      ota_password: !secret bar-light-01_ota_password
  device_type: !include ../../../device_types/ceiling-light.yaml
  linked-light: !include
    file: ../../../templates/single_linked-light.yaml
    vars:
      light_id: sylvania_smart_plus
      key: !secret bar-light-01_udp_key
      name_1: ${area}-bar-light-02
      key_1: !secret bar-light-02_udp_key

substitutions:
  node_name: "bar-light-01"
  friendly_name: "Kitchen Bar Light"