packages:
  base: !include 
    file: base.yaml
    vars:
      api_key: !secret sink-light_api_key
      ota_password: !secret sink-light_ota_password
  device_type: !include ../../../device_types/ceiling-light.yaml

substitutions:
  node_name: "sink-light"
  friendly_name: "Kitchen Sink Light"