packages:
  base: !include 
    file: base.yaml
    vars:
      api_key: !secret ceiling-light_api_key
      ota_password: !secret ceiling-light_ota_password
  device_type: !include ../../../device_types/ceiling-light.yaml
  linked-light: !include
    file: ../../../templates/double_linked-light.yaml
    vars:
      light_id: sylvania_smart_plus
      key: !secret ceiling-light_udp_key
      name_1: ${area}-dome-light-01
      key_1: !secret dome-light-01_udp_key
      name_2: ${area}-dome-light-02
      key_2: !secret dome-light-02_udp_key

substitutions:
  node_name: "ceiling-light"
  friendly_name: "Main Stairs Ceiling Light"