packages:
  base: !include 
    file: base.yaml
    vars:
      api_key: !secret lamp_01_api_key
      ota_password: !secret lamp_01_ota_password
  device_type: !include ../../../device_types/lamp_light.yaml

substitutions:
  node_name: "lamp_01"
  friendly_name: "Lamp Light"