packages:
  base: !include 
    file: base.yaml
    vars:
      api_key: !secret ceiling-light-03_api_key
      ota_password: !secret ceiling-light-03_ota_password
  device_type: !include ../../../device_types/ceiling-light.yaml
  linked-light: !include
    file: ../../../templates/double_linked-light.yaml
    vars:
      light_id: sylvania_smart_plus
      key: !secret ceiling-light-02_udp_key
      name_1: ${area}-ceiling-light-01
      key_1: !secret ceiling-light-01_udp_key
      name_2: ${area}-ceiling-light-03
      key_2: !secret ceiling-light-03_udp_key

substitutions:
  node_name: "ceiling-light-01"
  friendly_name: "Hallway Ceiling Light"