packages:
  base: !include 
    file: base.yaml
    vars:
      api_key: !secret lamp_post_api_key
      ota_password: !secret lamp_post_ota_password
  device_type: !include ../../../device_types/lamp_post_light.yaml

substitutions:
  node_name: "lamp_post"
  friendly_name: "Front Yard Lamp Post"