packages:
  base: !include
    file: base.yaml
    vars:
      api_key: !secret ceiling_light_02_api_key
      ota_password: !secret ceiling_light_02_ota_password
  device_type: !include ../../../device_types/ceiling_light.yaml

substitutions:
  node_name: "ceiling_light_02"
  friendly_name: "Hallway Ceiling Light"
  dns_name: "ceiling-light-02"
