packages:
  base: !include 
    file: base.yaml
    vars:
      api_key: !secret ceiling-light_api_key
      ota_password: !secret ceiling-light_ota_password
  device_type: !include ../../../device_types/ceiling-light.yaml

substitutions:
  node_name: "ceiling-light"
  friendly_name: "Garage Closet Ceiling Light"