esphome:
  name: ${area}_${node_name}
  friendly_name: ${friendly_name}
  area: ${area}

captive_portal:

external_components:
  - source:
      type: git
      url: https://github.com/robertklep/esphome-custom-component
    components: [ custom, custom_component ]