esphome:
  on_boot:
    priority: 600.0
    then:
      - script.execute: fast_boot_factory_reset_script

substitutions:
  factory_reset_boot_count_trigger: "5"

globals:
  - id: fast_boot
    type: int
    restore_value: yes
    initial_value: '0'

script:
  - id: fast_boot_factory_reset_script
    then:
      - if:
          condition:
            lambda: return ( id(fast_boot) >= ${factory_reset_boot_count_trigger});
          then:
            - lambda: |-
                ESP_LOGD("Fast Boot Factory Reset", "Performing factotry reset");
                id(fast_boot) = 0;
                fast_boot->loop();
                global_preferences->sync();
            - button.press: factory_reset_button
      - lambda: |-
          if(id(fast_boot) > 0)
            ESP_LOGD("Fast Boot Factory Reset", "Quick reboot %d/%d, do it %d more times to factory reset", id(fast_boot), ${factory_reset_boot_count_trigger}, ${factory_reset_boot_count_trigger} - id(fast_boot));
          id(fast_boot) += 1;
          fast_boot->loop();
          global_preferences->sync();
      - delay: 10s
      - lambda: |-
          id(fast_boot) = 0;
          fast_boot->loop();
          global_preferences->sync();

button:
  - platform: factory_reset
    id: factory_reset_button
    name: "ESPHome: Factory reset"