packages:
  base: !include
    file: base.yaml
    vars:
      api_key: !secret dome_light_01_api_key
      ota_password: !secret dome_light_01_ota_password
  device_type: !include ../../../device_types/dome_light.yaml

substitutions:
  node_name: "dome_light_01"
  friendly_name: "Garage Stairs Dome Light"
  dns_name: "dome-light-01"
