packages:
  base: !include 
    file: base.yaml
    vars:
      api_key: !secret dome_light_01_api_key
      ota_password: !secret dome_light_01_ota_password
  device_type: !include ../../../device_types/dome_light.yaml
  linked_light: !include
    file: ../../../templates/double_linked_light.yaml
    vars:
      light_id: sylvania_smart_plus
      key: !secret dome_light_01_udp_key
      name_1: ${area}_dome_light_02
      key_1: !secret dome_light_02_udp_key
      name_2: ${area}_ceiling_light
      key_2: !secret ceiling_light_udp_key

substitutions:
  node_name: "dome_light_01"
  friendly_name: "Garage Stairs Dome Light"