packages:
  esphome: !include ../../../common/esphome.yaml
  management_and_monitoring: !include ../../../common/management_and_monitoring.yaml
  factory_reset: !include ../../../common/factory_reset.yaml
  light: !include ../../components/light.yaml
  output: !include ../../components/output.yaml

network:
  enable_ipv6: true

api:

mdns:
  disabled: true

esphome:
  name_add_mac_suffix: true

wifi:
  use_address: "${dns_area}-${dns_name}"
  fast_connect: true

  ap:
    ssid: ${area}_${node_name}

ota:
  - platform: esphome
    id: esphome_ota
    on_begin:
      then:
        - logger.log: 
            format: "Starting ESPHome OTA Update"
            level: INFO
            tag: ota.esphome
    on_progress:
      then:
        - logger.log: 
            format: "ESPHome OTA Progess %0.1f%%"
            args: ["x"]
            level: INFO
            tag: ota.esphome
    on_end:
      then:
        - logger.log: 
            format: "ESPHome OTA Update Complete"
            level: INFO
            tag: ota.esphome
    on_error:
      then:
        - logger.log:
            format: "ESPHome OTA Update Error %d"
            args: ["x"]
            level: INFO
            tag: ota.esphome

substitutions:
  floor: "generic"
