packages:
  base: !include
    file: base.yaml
    vars:
      api_key: !secret mirror_light_02_api_key
      ota_password: !secret mirror_light_02_ota_password
  device_type: !include ../../../device_types/mirror_light.yaml

substitutions:
  node_name: "mirror_light_02"
  friendly_name: "Grey's Bathroom Mirror Light"
  dns_name: "mirror-light-02"
