substitutions:
  device_type: generic_light

esphome:
  on_boot:
    priority: 700
    then:
      - light.turn_on:
          id: "sylvania_smart_plus"
          color_mode: COLOR_TEMPERATURE
          brightness: 100%
          color_temperature: 2000K
  includes:
    - ../../../custom_components/ghomedimmer_uart_slider.h

bk72xx:
  board: generic-bk7231t-qfn32-tuya