packages:
  base: !include 
    file: base.yaml
    vars:
      api_key: !secret wall-lamp_api_key
      ota_password: !secret wall-lamp_ota_password
  device_type: !include ../../../device_types/wall-lamp-light.yaml

substitutions:
  node_name: "wall-lamp"
  friendly_name: "Driveway Wall Lamp"