packages:
  base: !include 
    file: base.yaml
    vars:
      api_key: !secret dome-light-02_api_key
      ota_password: !secret dome-light-02_ota_password
  device_type: !include ../../../device_types/dome-light.yaml
  linked-light: !include
    file: ../../../templates/double_linked-light.yaml
    vars:
      light_id: sylvania_smart_plus
      key: !secret dome-light-02_udp_key
      name_1: ${area}-dome-light-01
      key_1: !secret dome-light-01_udp_key
      name_2: ${area}-ceiling-light
      key_2: !secret ceiling-light_udp_key

substitutions:
  node_name: "dome-light-02"
  friendly_name: "Garage Stairs Dome Light"