packages:
  esphome: !include ../common/esphome.yaml
  network_hardware: !include ../common/network_hardware.yaml
  network_protocols: !include 
    file: ../common/network_protocols.yaml
    vars:
      api_key: ${api_key}
  management_and_monitoring: !include ../common/management_and_monitoring.yaml
  update_installation: !include 
    file: ../common/update_installation.yaml
    vars:
      ota_password: ${ota_password}
  light_components: !include ../components/lights.yaml
  output_components: !include ../components/outputs.yaml