packages:
  base: !include
    file: base.yaml
    vars:
      api_key: !secret bar_light_01_api_key
      ota_password: !secret bar_light_01_ota_password
  device_type: !include ../../../device_types/ceiling_light.yaml

substitutions:
  node_name: "bar_light_01"
  friendly_name: "Kitchen Bar Light"
  dns_name: "bar-light-01"
