packages:
  floor_base: !include
    file: ../base.yaml
    vars:
      api_key: ${api_key}
      ota_password: ${ota_password}

esphome:
  name_add_mac_suffix: true

substitutions:
  area: "gnrc"
  dns_area: "gnrc"
