packages:
  base: !include base.yaml
  device_type: !include ../../../device_types/fake_light_switch.yaml

substitutions:
  node_name: "fake_light_switch"
  friendly_name: "Generic Fake Light Switch"
  dns_name: "fake-light-switch"
