packages:
  base: !include base.yaml
  device_type: !include ../../../device_types/fan_switch.yaml

substitutions:
  node_name: "fan_switch"
  friendly_name: "Generic Fan Switch"
  dns_name: "fan-switch"
