packages:
  base: !include base.yaml
  device_type: !include ../../../device_types/real_light_switch.yaml

substitutions:
  node_name: "real_light_switch"
  friendly_name: "Generic Real Light Switch"
  dns_name: "real_light_switch"
