packages:
  base: !include base.yaml
  device_type: !include ../../../device_types/smart_switch.yaml

substitutions:
  node_name: "smart_switch"
  friendly_name: "Generic Smart Switch"
  dns_name: "smart-switch"
