packages:
  base: !include base.yaml
  device_type: !include ../../../device_types/ceiling_fan_light.yaml

substitutions:
  node_name: "ceiling_fan_light"
  friendly_name: "Generic Ceiling Fan Light"
  dns_name: "ceiling-fan-light"
