packages:
  base: !include base.yaml
  device_type: !include ../../../device_types/ceiling_light.yaml

substitutions:
  node_name: "ceiling_light"
  friendly_name: "Generic Ceiling Light"
  dns_name: "ceiling-light"
