packages:
  base: !include base.yaml
  device_type: !include ../../../device_types/closet_light.yaml

substitutions:
  node_name: "closet_light"
  friendly_name: "Generic Closet Light"
  dns_name: "closet-light"
