packages:
  base: !include base.yaml
  device_type: !include ../../../device_types/mirror_light.yaml

substitutions:
  node_name: "mirror_light"
  friendly_name: "Generic Mirror Light"
  dns_name: "mirror-light"
