packages:
  base: !include base.yaml
  device_type: !include ../../../device_types/shower_light.yaml

substitutions:
  node_name: "shower_light"
  friendly_name: "Generic Shower Light"
  dns_name: "shower-light"
