packages:
  base: !include base.yaml
  device_type: !include ../../../device_types/wall_lamp_light.yaml

substitutions:
  node_name: "wall_lamp_light"
  friendly_name: "Generic Wall Lamp Light"
  dns_name: "wall-lamp-light"
